#!/usr/bin/env python

# Import Standard Libary Packages
import pathlib
import pickle
import pkg_resources

def get_dict() -> dict:
    with open('dict.pkl', 'rb') as pickle_dict:
        return pickle.load(pickle_dict)